---
- name: Add repository PostgreSQL key
  apt_key: 
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name:  Add repository PostgreSQL 
  apt_repository: 
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main" 

- name: Install PostgreSQL
  apt:
    name:
      - "postgresql-{{ postgres_version }}"
      - "postgresql-client-{{ postgres_version }}"
    update_cache: yes
  ignore_errors: "{{ ansible_check_mode }}"

- name: Copy PostgreSQL configuration file
  template:
    src: postgresql.conf.j2
    dest: "{{ postgres_config_path }}/postgresql.conf"
    owner: postgres
    mode: 0644
  notify: restart postgresql

- name: Make sure psycopg2 is installed (required for postgresql_user)
  pip:
    name: psycopg2-binary
    state: present

- name: Check if PostgreSQL database is initialized
  stat:
    path: "{{ postgres_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: Make sure PostgreSQL database is initialized
  command: "{{ postgres_bin_path }}/initdb -D {{ postgres_data_dir }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "{{ postgres_user }}"
  vars:
    ansible_ssh_pipelining: true

- name: Set postgres user password
  postgresql_user:
    user: postgres
    password:  "{{ postgres_pass }}"
    encrypted: yes
  become: yes
  become_user: postgres