---
- name: Enable nginx service
  become: yes
  hosts: webserver
  tasks:

    - name: Install Nginx
      apt:
        name: nginx-extras
        update-cache: yes

    - name: Start nginx service
      systemd:
        name: nginx
        state: started

    - name: Replace default web page
      copy: 
        src: index.html
        dest: /var/www/html/index.html
        mode: 0644
    
    - name: Update nginx config
      copy: 
        src: nginx.conf 
        dest: /etc/nginx/sites-enabled/default
        mode: 0644
      notify: restart nginx