---
- name: Install default packages to Debian family 
  apt:
    name: "{{ item }}"
    update_cache: yes
    autoremove: yes
  with_items:
    - iotop
    - htop
    - mc
    - net-tools
  when: ansible_os_family == 'Debian'
    
- name: Install default packages to RedHat family 
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - iotop
    - htop
    - mc
    - net-tools
  when: ansible_os_family == 'RedHat'