---
- name: Enable nginx service
  become: yes
  hosts: webserver
  tasks:
    #- set_fact:
    #    nginx_status: no

    #- name: Print variable
    #  debug:
    #    msg: "{{ nginx_status }}" 

    - name: Install Nginx
      apt:
        name: nginx-extras
        update-cache: yes

    - name: Start nginx service
      systemd:
        name: nginx
        state: started
      register: result

    - name: Print resilt
      debug: 
        msg: "{{ result['state']  }}"

    #- name: Stop nginx service
    #  systemd:
    #    name: nginx
    #    state: stopped
    #  when: not nginx_status

    - name: Replace default web page
      copy: 
        src: index.html
        dest: /var/www/html/index.html
        mode: 0644
    
    - name: Update nginx config
      copy: 
        src: nginx.conf 
        dest: /etc/nginx/sites-enabled/default
        mode: 0644
      notify: restart nginx


  handlers: 
    - name: restart nginx
      systemd:
        daemon_reload: true
        name: nginx
        state: restarted
        register: restart_nginx_result
        ignore_errors: true